[[CURRENCIES]]
code = "PALESTINE"
issuer = "GCQMZWLH3F26EWSLMVLCR3KVL2LLERFEMMEBV56S5C3OLD56VR7RGAHL"
display_decimals = 7
name = "Palestine Token"
desc = "A symbolic token representing the spirit of Palestine on Pi Network."
image = "https://zaidplt22.github.io/plt/logo.png"
