[[CURRENCIES]]
code = "PALESTINE"
issuer = "GCQMZWLH3F26EWSLMVLCR3KVL2LLERFEMMEBV56S5C3OLD56VR7RGAHL"
display_decimals = 7
name = "Palestine Token"
desc = "A symbolic token representing the spirit of Palestine on Pi Network."
image = "https://zaid700839130-sys.github.io/palestine-token/1776453663234.png"
