ACCOUNTS=["GATKJ3MHLERAXXXNS2VGGT5HP3HSXD53THCRYCFOTYSNOBUCRNUILKYE"]

[ORG]
NAME="PALESTINE"
URL="https://zaidplt22.github.io/plt/"
LOGO="https://zaidplt22.github.io/plt/logo.png"

[[CURRENCIES]]
code="PALESTINE"
issuer="GATKJ3MHLERAXXXNS2VGGT5HP3HSXD53THCRYCFOTYSNOBUCRNUILKYE"
display_decimals=7
name="PALESTINE"
desc="عملة فلسطين الرقمية - قضية وطن في عالم الرقميات"
conditions="Testnet Currency"
image = "https://zaidplt22.github.io/plt/logo.png"
