[[CURRENCIES]]
code="PALESTINE"
issuer="GCQMZWLH3F26EWSLMVLCR3KVL2LLERFEMMEBV56S5C3OLD56VR7RGAHL"
display_decimal=7
name="PALESTINE"
desc="عملة فلسطين الرقمية الموثقة"
image="https://zaidplt22.github.io/plt/logo.png"
